# Gaussian Channel Configuration

gaussian:
  # Pine Script parameters
  poles: 4
  period: 144
  multiplier: 1.414
  reduced_lag: false
  fast_response: false
  
  # Analysis settings
  analysis_30m:
    timeframe: "15m"  # Testing on 15m, will be 30m in production
    check_bands: true
    check_filter: false  # Only upper/lower bands for 30m
    
  analysis_4h:
    timeframe: "4h"
    check_bands: true
    check_filter: true  # All 3 lines for 4h

# Data fetching
data:
  candle_limit: 200  # Need enough data for Gaussian calculation
  
# Alert settings
alerts:
  mode: "test"  # test or production
  duplicate_prevention: true
  consolidate_multi_line: true

# Telegram (uses environment variables)
telegram:
  enabled: true
  timeout: 10
